In [3]:
# RELU ACTIVATION FUNCTION
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

class Activation_RELU:
    
    def forward_pass(self, inputs):
        self.output = np.maximum(0, inputs)



In [8]:
class Layer_Dense:

    def __init__(self, n_inputs, n_neurons):
        #Init weights, biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    # Forward pass
    def forward_pass(self, inputs):
        # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases
        

In [9]:
nnfs.init()

In [10]:
# Create Dataset
X, y = spiral_data(samples=100, classes=3)

# Layer 1 -> 2 input and 3 output values
dense1 = Layer_Dense(2, 3)

# RELU use
activation1 = Activation_RELU()

dense1.forward_pass(X)

activation1.forward_pass(dense1.output)


In [11]:
print(activation1.output[:5])

[[0.         0.         0.        ]
 [0.         0.00011395 0.        ]
 [0.         0.00031729 0.        ]
 [0.         0.00052666 0.        ]
 [0.         0.00071401 0.        ]]


In [12]:
# SOFTMAX ACTIVATION FUNCTION

layer_outputs = [4.8, 1.21, 2.385]

# for each value, calculate the exp using np.exp
exp_values = np.exp(layer_outputs)
print(f"Exponential Values : {exp_values}")

# Normalize the calculated values

norm_values = exp_values / np.sum(exp_values)
print(f"Normalized Exponential Values : {norm_values}")
print(f"Sum of Normalized Values : {np.sum(norm_values)}")


Exponential Values : [121.51041752   3.35348465  10.85906266]
Normalized Exponential Values : [0.89528266 0.02470831 0.08000903]
Sum of Normalized Values : 0.9999999999999999


In [15]:
class Activation_Softmax:
    def forward(self, inputs):
        # unnormalized Probabilites
        exp_values = np.exp(inputs - np.max(inputs, axis=1, 
                                            keepdims=True))
        
        # Normalize the values
        probs = exp_values / np.sum(exp_values, axis=1,
                                    keepdims=True)
        
        self.output = probs

In [16]:
softmax = Activation_Softmax()

softmax.forward([[1,2,3]])
print(softmax.output)

[[0.09003057 0.24472847 0.66524096]]


In [19]:
# ZIPPING thE ENTIRE CODE

dense1 = Layer_Dense(2,3)

activation1 = Activation_RELU()

dense2 = Layer_Dense(3,3)

activation2 = Activation_Softmax()

dense1.forward_pass(X)

activation1.forward_pass(dense1.output)

dense2.forward_pass(activation1.output)

activation2.forward(dense2.output)


In [20]:
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.3333335  0.33333305 0.3333335 ]
 [0.33333352 0.333333   0.33333352]]
